# Generated by Django 4.0.5 on 2022-07-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(unique=True, verbose_name='آدرس')),
                ('name', models.CharField(max_length=100, verbose_name='نام سایت')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='لوگو')),
            ],
        ),
    ]
